project:
  type: website

website:
  title: "SIB_Course"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis.qmd
      - href: interactive_compute.qmd
        text: static interactive compute

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true